version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

deploy-tags: &deploy-tags
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/

jobs:
  containers:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker
      - run: |
          # use the tag name or commit hash
          export CONTAINER_TAG=$(git describe --tags --dirty --always)
          docker build . -t 376424775662.dkr.ecr.us-east-2.amazonaws.com/imagepullscret-patcher:${CONTAINER_TAG/v/}
          docker login -u AWS -p $(aws ecr get-login-password) https://376424775662.dkr.ecr.us-east-2.amazonaws.com
          docker push 376424775662.dkr.ecr.us-east-2.amazonaws.com/imagepullscret-patcher:${CONTAINER_TAG/v/}

workflows:
  version: 2
  deploy:
    jobs:
      - containers:
          filters:
            branches:
              only: [master]
          context:
            - aws-ecr
